//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paravaly.Resources {
    using System;
    using System.Reflection;


    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        internal ErrorMessage() {
        }

        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paravaly.Resources.ErrorMessage", typeof(ErrorMessage).GetInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The array contains one or more invalid elements..
        /// </summary>
        public static string ForArrayAll {
            get {
                return ResourceManager.GetString("ForArrayAll", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The array contains one or more invalid elements..
        /// </summary>
        public static string ForArrayAny {
            get {
                return ResourceManager.GetString("ForArrayAny", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The array can&apos;t contain null elements..
        /// </summary>
        public static string ForArrayHasNoNullElements {
            get {
                return ResourceManager.GetString("ForArrayHasNoNullElements", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The array can&apos;t be empty..
        /// </summary>
        public static string ForArrayIsNotEmpty {
            get {
                return ResourceManager.GetString("ForArrayIsNotEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The array contains one or more invalid elements..
        /// </summary>
        public static string ForArrayNone {
            get {
                return ResourceManager.GetString("ForArrayNone", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value should contain the text: &apos;{0}&apos;. Actual value: {1}..
        /// </summary>
        public static string ForContains {
            get {
                return ResourceManager.GetString("ForContains", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The dictionary should contain the key: &apos;{0}&apos;..
        /// </summary>
        public static string ForContainsKey {
            get {
                return ResourceManager.GetString("ForContainsKey", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value should not contain the text: &apos;{0}&apos;. Actual value: {1}..
        /// </summary>
        public static string ForDoesNotContain {
            get {
                return ResourceManager.GetString("ForDoesNotContain", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value should not end with the text &apos;{0}&apos;. Actual value: &apos;{1}&apos;..
        /// </summary>
        public static string ForDoesNotEndWith {
            get {
                return ResourceManager.GetString("ForDoesNotEndWith", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value should not start with the text &apos;{0}&apos;. Actual value: &apos;{1}&apos;..
        /// </summary>
        public static string ForDoesNotStartWith {
            get {
                return ResourceManager.GetString("ForDoesNotStartWith", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value should end with the text &apos;{0}&apos;. Actual value: &apos;{1}&apos;..
        /// </summary>
        public static string ForEndsWith {
            get {
                return ResourceManager.GetString("ForEndsWith", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter count is outside the allowable range of values. Minimum: {0}. Maximum: {1}. Actual value: {2}..
        /// </summary>
        public static string ForHasCountWithinRange {
            get {
                return ResourceManager.GetString("ForHasCountWithinRange", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter length is outside the allowable range of values. Minimum: {0}. Maximum: {1}. Actual value: {2}..
        /// </summary>
        public static string ForHasLengthWithinRange {
            get {
                return ResourceManager.GetString("ForHasLengthWithinRange", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The collection contains one or more invalid elements..
        /// </summary>
        public static string ForICollectionAll {
            get {
                return ResourceManager.GetString("ForICollectionAll", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The collection contains one or more invalid elements..
        /// </summary>
        public static string ForICollectionAny {
            get {
                return ResourceManager.GetString("ForICollectionAny", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The collection can&apos;t contain null elements..
        /// </summary>
        public static string ForICollectionHasNoNullElements {
            get {
                return ResourceManager.GetString("ForICollectionHasNoNullElements", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The collection can&apos;t be empty..
        /// </summary>
        public static string ForICollectionIsNotEmpty {
            get {
                return ResourceManager.GetString("ForICollectionIsNotEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The collection contains one or more invalid elements..
        /// </summary>
        public static string ForICollectionNone {
            get {
                return ResourceManager.GetString("ForICollectionNone", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter is not of type &apos;{0}&apos;. Actual type: {1}..
        /// </summary>
        public static string ForInvalidType {
            get {
                return ResourceManager.GetString("ForInvalidType", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value is not a class type..
        /// </summary>
        public static string ForIsClass {
            get {
                return ResourceManager.GetString("ForIsClass", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value is not an enumeration..
        /// </summary>
        public static string ForIsEnum {
            get {
                return ResourceManager.GetString("ForIsEnum", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter should be greater than {0}. Actual value: {1}..
        /// </summary>
        public static string ForIsGreaterThan {
            get {
                return ResourceManager.GetString("ForIsGreaterThan", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter should be greater than or equal to {0}. Actual value: {1}..
        /// </summary>
        public static string ForIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("ForIsGreaterThanOrEqualTo", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value is not valid. Valid Values: {0}. Actual value: {1}..
        /// </summary>
        public static string ForIsIn {
            get {
                return ResourceManager.GetString("ForIsIn", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value is not an interface type..
        /// </summary>
        public static string ForIsInterface {
            get {
                return ResourceManager.GetString("ForIsInterface", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter should be less than {0}. Actual value: {1}..
        /// </summary>
        public static string ForIsLessThan {
            get {
                return ResourceManager.GetString("ForIsLessThan", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter should be less than or equal to {0}. Actual value: {1}..
        /// </summary>
        public static string ForIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("ForIsLessThanOrEqualTo", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value doesn&apos;t match the regular expression. Regular Expression: {0}. Actual value: {1}..
        /// </summary>
        public static string ForIsMatch {
            get {
                return ResourceManager.GetString("ForIsMatch", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value is a class type..
        /// </summary>
        public static string ForIsNotClass {
            get {
                return ResourceManager.GetString("ForIsNotClass", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter should not be empty..
        /// </summary>
        public static string ForIsNotEmpty {
            get {
                return ResourceManager.GetString("ForIsNotEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value is an enumeration..
        /// </summary>
        public static string ForIsNotEnum {
            get {
                return ResourceManager.GetString("ForIsNotEnum", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value is one of a list of invalid values. Invalid Values: {0}. Actual value: {1}..
        /// </summary>
        public static string ForIsNotIn {
            get {
                return ResourceManager.GetString("ForIsNotIn", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value is infinity..
        /// </summary>
        public static string ForIsNotInfinity {
            get {
                return ResourceManager.GetString("ForIsNotInfinity", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value is an interface type..
        /// </summary>
        public static string ForIsNotInterface {
            get {
                return ResourceManager.GetString("ForIsNotInterface", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value is not a number..
        /// </summary>
        public static string ForIsNotNaN {
            get {
                return ResourceManager.GetString("ForIsNotNaN", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value is negative infinity..
        /// </summary>
        public static string ForIsNotNegativeInfinity {
            get {
                return ResourceManager.GetString("ForIsNotNegativeInfinity", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value is positive infinity..
        /// </summary>
        public static string ForIsNotPositiveInfinity {
            get {
                return ResourceManager.GetString("ForIsNotPositiveInfinity", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value is a value type..
        /// </summary>
        public static string ForIsNotValueType {
            get {
                return ResourceManager.GetString("ForIsNotValueType", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter should not contain white space only..
        /// </summary>
        public static string ForIsNotWhiteSpace {
            get {
                return ResourceManager.GetString("ForIsNotWhiteSpace", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value is not valid for enumeration type &apos;{0}&apos;. Actual value: {1}..
        /// </summary>
        public static string ForIsValidEnumValue {
            get {
                return ResourceManager.GetString("ForIsValidEnumValue", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value is not a value type..
        /// </summary>
        public static string ForIsValueType {
            get {
                return ResourceManager.GetString("ForIsValueType", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter is outside the allowable range of values. Minimum: {0}. Maximum: {1}. Actual value: {2}..
        /// </summary>
        public static string ForIsWithinRange {
            get {
                return ResourceManager.GetString("ForIsWithinRange", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter type is not assignable to type &apos;{0}&apos;. Actual type: {1}..
        /// </summary>
        public static string ForNotAssignableType {
            get {
                return ResourceManager.GetString("ForNotAssignableType", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter value should start with the text &apos;{0}&apos;. Actual value: &apos;{1}&apos;..
        /// </summary>
        public static string ForStartsWith {
            get {
                return ResourceManager.GetString("ForStartsWith", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter length is not valid. Actual Length: {0}. Expected Length: {1}..
        /// </summary>
        public static string ForStringHasLength {
            get {
                return ResourceManager.GetString("ForStringHasLength", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to The parameter should be different from &apos;{0}&apos;. Actual type: {1}..
        /// </summary>
        public static string ForStringIsNotEqualTo {
            get {
                return ResourceManager.GetString("ForStringIsNotEqualTo", resourceCulture);
            }
        }
    }
}
